language: go

branches:
  only:
    - "master"
    - "develop"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - dep ensure
  - cd $GOPATH
  - curl -L https://git.io/vp6lP | sh
  - cd $TRAVIS_BUILD_DIR

# Only clone the most recent commit.
git:
  depth: 1

go:
  - "1.10"

env:
  - DEP_VERSION=0.5.0

script:
  - make test lint

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
